# Generated by Django 3.2.13 on 2022-05-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220526_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
