# Generated by Django 3.2.13 on 2022-05-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='title',
        ),
    ]
